# Generated by Django 5.2.6 on 2025-09-11 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titlu')),
                ('description', models.TextField(verbose_name='Descriere')),
                ('date_added_str', models.CharField(help_text='Format acceptat: YYYY-MM-DD HH:MM[:SS] — se salvează ca YYYY-MM-DD HH:MM:SS', max_length=19, verbose_name='Data de adăugare (string)')),
                ('cook_time', models.CharField(max_length=50, verbose_name='Timp de gătire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creat la')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'rețetă',
                'verbose_name_plural': 'rețete',
                'ordering': ['title'],
            },
        ),
    ]
